name: qa-challenge-automation

on:
    push:
        branches: [ main, Qa-challengs-2 ]
    pull_request:
        branches: [ main, Qa-challengs-2 ]
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18.x]

        steps:
            - name: Checkout
                uses: actions/checkout@v3

            - name: Setup Node.js
                uses: actions/setup-node@v3
                with:
                    node-version: ${{ matrix.node-version }}
                    cache: 'npm'

            - name: Cache node modules
                uses: actions/cache@v3
                with:
                    path: ~/.npm
                    key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                    restore-keys: |
                        ${{ runner.os }}-node-

            - name: Install dependencies
                run: npm ci

            - name: Build (if present)
                run: npm run build --if-present

            # Start app in background so E2E can run against it.
            # Ajusta http://localhost:3000 al URL/puerto que use tu app.
            - name: Start app
                run: |
                    if npm run | grep -q "start"; then
                        nohup npm run start &>/dev/null &
                        echo "Waiting for app to be available on http://localhost:3000..."
                        npx wait-on http://localhost:3000 -t 120000
                    else
                        echo "No start script found, skipping app start"
                    fi

            - name: Install browsers for Playwright (no-op if not used)
                run: npx playwright install --with-deps || true

            - name: Run linter
                run: npm run lint

            - name: Run unit tests
                run: npm test

            - name: Run E2E tests
                run: npm run test:e2e

            - name: Upload test results
                if: ${{ always() }}
                uses: actions/upload-artifact@v3
                with:
                    name: test-results
                    path: test-results/